---

- name: "Install nginx"
  become: yes
  apt: name=nginx state=latest

- name: "Create the Nginx configuration file"
  become: yes
  template: src="{{ nginx_template }}" dest="/etc/nginx/sites-available/{{ application_name }}" backup=yes
  notify: reload nginx

- name: "Ensure that the default site is disabled"
  become: yes
  file: path="/etc/nginx/sites-enabled/default" state=absent
  notify: reload nginx

- name: "Ensure that the application site is enabled"
  become: yes
  file:
    src="/etc/nginx/sites-available/{{ application_name }}"
    dest="/etc/nginx/sites-enabled/{{ application_name }}"
    state=link
  notify: reload nginx

- name: "Ensure Nginx service is started"
  become: yes
  service: name=nginx state=started enabled=yes
